### ISSUE TITLE
code cleanup checklist

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-fish-tools/SSMSE#61]
Some small style things to clean up before a first version. Most of these would be good to do after most active development is done, to avoid confusion between commits made to improve code style or code function.

- [x] Run styler to format code
- [x] Run r4ss::rm_dollar_sign to get rid of refs made with `$` (dollar sign is not prefered because it allows partial matching)
- [x] Delete commented out code that is unlikely to be needed in the future
- [x] Clean up any unnecessary or outdated comments. When possible, make comments clearer (but don't spend too much time on this
- [x] Run devtools::document
- [x] Update documentation by rendering locally
